### ISSUE TITLE
SINHA_2016 genera counts are not counts

### ISSUE THREAD

**Issue by mdanb** [borenstein-lab/microbiome-metabolome-curated-data#10]
Hi,

The `genera.counts.tsv` file for SINHA_2016 doesn't seem to actually contain counts since they're not integers.

**Comment by efratmuller** [comment]
You are right! As the 16S reads were not available for this particular dataset, we used relative abundance profiles as provided in the paper's supplementary data. Read counts are therefore unavailable and this file was produced by mistake. It is deleted now, and a note was added to the Wiki. Thanks, Efrat
