### ISSUE TITLE
data/processed_data/iHMP_IBDMDB_2019/mtb.tsv.zip does not open

### ISSUE THREAD

**Issue by htpusa** [borenstein-lab/microbiome-metabolome-curated-data#3]
I'm getting a "The archive is empty" when trying to unzip the file.

**Comment by efratmuller** [comment]
Hi, I'm not sure why that happened but I've just pushed a proper zip so please re-download and try again.

**Comment by htpusa** [comment]
Works now!

**Comment by Benjamin-Valderrama** [comment]
Hello @efratmuller ,

I'm facing now the same issue. Is there an alternative way to access the same dataset?

**Comment by efratmuller** [comment]
Hi! I found the bug causing damaged zip files. It's fine now so please pull the zip file again...
