### ISSUE TITLE
Shared names file/dataframe missing

### ISSUE THREAD

**Issue by microbemarsh** [borenstein-lab/microbiome-metabolome-curated-data#7]
Hi Efrat,

Thank you for putting together this great resource, I was working through the [meta-analysis_of_genus_metabolite_associations.Rmd](https://github.com/borenstein-lab/microbiome-metabolome-curated-data/blob/main/scripts/data_analysis/meta-analysis_of_genus_metabolite_associations.Rmd) and ran into an issue in the fourth chunk where I cannot seem to load in the `Shared.w.ERAWIJANTARI_2020` dataframe. I looked throughout the github as well and couldn't find it, any help would be greatly appreciated!

In Thanks,
Austin

**Comment by efratmuller** [comment]
Hi Austin!
Thanks for your interest in this resource. I re-ran the notebook and the forth chunk ran fine, so lets try and figure out what went wrong in your local clone. First of all, `Shared.w.ERAWIJANTARI_2020` is a name of a column within the `metadata$YACHIDA_CRC_2019` table. Can you please run `colnames(metadata$YACHIDA_CRC_2019)` before executing the forth chunk and paste here what you get?
This is what I get:
<img width="371" alt="image" src="https://github.com/borenstein-lab/microbiome-metabolome-curated-data/assets/5261766/c099ae9b-fa20-4274-a723-4d540bda5393">

Best,
Efrat

**Comment by microbemarsh** [comment]
It might just stem from where the work dir is set with my script, within the cloned github where do you `setwd`?

**Comment by efratmuller** [comment]
`microbiome-metabolome-curated-data/scripts`

**Comment by microbemarsh** [comment]
Yep that was the issue, oh my goodness sorry. Shouldn't be working late sometimes!

**Comment by microbemarsh** [comment]
Yep that was the issue, oh my goodness sorry. Shouldn't be working late sometimes!

**Comment by efratmuller** [comment]
No worries :)
